### ISSUE TITLE
What about developer oriented plugins not allowed in the official repo?

### ISSUE THREAD

**Issue by afragen** [Freemius/IncludeWP#24]
Just curious whether I should submit GitHub Updater, https://github.com/afragen/github-updater

**Comment by vovafeldman** [comment]
@afragen does it match the criteria?

![image](https://cloud.githubusercontent.com/assets/6830121/17641344/3559da78-60e9-11e6-8bde-cae4f78d4cf1.png)

**Comment by afragen** [comment]
Regrettably no. While it requires plugins and themes to work, it is designed to not be included inside another project. It's designed to be included along side. :disappointed:
